version: '3.8'

services:
  # Laravel Application (Production)
  app:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    volumes:
      - ./:/var/www/html
    expose:
      - "8000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=erp-studio3d.cng8secmmw73.eu-north-1.rds.amazonaws.com
      - DB_PORT=3306
      - DB_DATABASE=erp_studio5d_1
      - DB_USERNAME=admin
      - DB_PASSWORD=Kilo15.35
    networks:
      - app-network

  # Nginx Service (Production only)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"      # HTTP only
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - app-network

  # PHPMyAdmin for RDS
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: erp-studio3d.cng8secmmw73.eu-north-1.rds.amazonaws.com
      PMA_PORT: 3306
      PMA_USER: admin
      PMA_PASSWORD: Kilo15.35
      PMA_ARBITRARY: 1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

